//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace circus_praktica.DBConnection
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cell
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cell()
        {
            this.Training_Schedule = new HashSet<Training_Schedule>();
        }
    
        public int Id_Animal_Cell { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> BDay { get; set; }
        public Nullable<int> Id_Gender { get; set; }
        public Nullable<int> Weight { get; set; }
        public string Food_Preferences { get; set; }
        public string Recommendations_for_care { get; set; }
        public Nullable<int> Id_Animal_trainer { get; set; }
    
        public virtual Animal_trainer Animal_trainer { get; set; }
        public virtual Gender Gender { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Training_Schedule> Training_Schedule { get; set; }
    }
}
