//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace circus_praktica.DBConnection
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tasks
    {
        public int Kod_Task { get; set; }
        public Nullable<int> Id_Admin { get; set; }
        public Nullable<int> Id_Staff { get; set; }
        public string Description { get; set; }
        public Nullable<bool> Done { get; set; }
        public string Comment { get; set; }
    
        public virtual Admins Admins { get; set; }
        public virtual Staff Staff { get; set; }
    }
}
