//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace circus_praktica.DBConnection
{
    using System;
    using System.Collections.Generic;
    
    public partial class Training_Schedule
    {
        public int Id_Shedule { get; set; }
        public int Id_Animal_Cell { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<System.TimeSpan> Time { get; set; }
        public Nullable<bool> Done { get; set; }
        public string Description { get; set; }
    
        public virtual Cell Cell { get; set; }
    }
}
